import\t{\tuseState\t}\tfrom\t'react';
import\t{\tuseRouter\t}\tfrom\t'next/router';
import\tLink\tfrom\t'next/link';

const\tAddPiece\t=\t({})\t=>\t{
	const\trouter\t=\tuseRouter();
	const\t{\tupdate,\twritingId,\ttitle,\tsummary,\tfinished,\ttype\t}\t=\trouter.query;
	let\t[titleHook,\tsetTitle]\t=\tuseState(title\t?\ttitle\t:\t'');
	let\t[summaryHook,\tsetSummary]\t=\tuseState(summary\t?\tsummary\t:\t'');
	let\t[finishedHook,\tsetFinished]\t=\tuseState(finished\t?\tfinished\t:\tfalse);

	return\t(
		<div\tclassName="add-piece\tcontainer\tmt-5">
			<Link\thref="/pieces/roll">Back\tTo\tRoll</Link>
			<form
				className="form"
				onSubmit={async\t(e)\t=>\t{
					e.preventDefault();
					const\tres\t=\tawait\tfetch('/api/writing/add_or_update',\t{
						method:\t'POST',
						headers:\t{
							Accept:\t'application/json',
							'Content-Type':\t'application/json'
						},
						body:\tJSON.stringify({
							update,
							_id:\twritingId,
							titleHook,
							summaryHook,
							finishedHook,
							type
						})
					});
					const\treturnedData\t=\tawait\tres.json();
					if\t(res.ok)\t{
						router.push('/pieces/roll');
					}\telse\t{
						console.log(
							'Error\tin\tpiece/add_or_update:',
							returnedData.errorMessage
						);
					}
				}}
			>
				<label\thtmlFor="title">
					Title
					<input
						name="title"
						type="text"
						value={titleHook}
						onInput={(e)\t=>\t{
							setTitle(e.target.value);
						}}
					></input>
				</label>
				<div\tclassName="status">
					<span>Status:\t</span>
					<label\thtmlFor="title">
						Finished
						<input
							name="title"
							type="radio"
							defaultChecked={finishedHook\t===\t'true'}
							onClick={()\t=>\t{
								setFinished(true);
							}}
						></input>
					</label>
					<label\thtmlFor="title">
						Ongoing
						<input
							name="title"
							type="radio"
							defaultChecked={
								finishedHook\t===\t'false'\t||\t!finishedHook
							}
							onClick={()\t=>\t{
								setFinished(false);
							}}
						></input>
					</label>
				</div>
				<label\thtmlFor="summary">
					Summary
					<textarea
						name="summary"
						type="text"
						value={summaryHook}
						onInput={(e)\t=>\t{
							setSummary(e.target.value);
						}}
					></textarea>
				</label>
				<button>Submit</button>
			</form>
		</div>
	);
};

export\tdefault\tAddPiece;
